/** schema sql **/

CREATE DATABASE db_jpa;

use db_jpa;

create table PRODUK(
    PRODUK_ID INT AUTO_INCREMENT NOT NULL UNIQUE,
    PRODUK_CODE VARCHAR(255) NOT NULL,
    PRODUK_NAME VARCHAR(255) NOT NULL,

    CONSTRAINT PK_PRODUK_PRODUK_ID PRIMARY KEY (PRODUK_ID)
);

create table KATEGORI(
    KATEGORI_ID INT AUTO_INCREMENT NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,

    CONSTRAINT PK_KATEGORI_KATEGORI_ID PRIMARY KEY (KATEGORI_ID)
);

create table PRODUK_KATEGORI(
    PRODUK_ID INT NOT NULL,
    KATEGORI_ID INT NOT NULL,
    CREATED_DATE DATE NOT NULL,
    CREATED_BY VARCHAR(255) NOT NULL,

    PRIMARY KEY (PRODUK_ID, KATEGORI_ID),
    CONSTRAINT PK_PRODUK_KATEGORI_PRODUK_ID FOREIGN KEY (PRODUK_ID)
    REFERENCES PRODUK (PRODUK_ID),
    CONSTRAINT PK_PRODUK_KATEGORI_KATEGORI_ID FOREIGN KEY (KATEGORI_ID)
    REFERENCES KATEGORI (KATEGORI_ID)
);